import { usePlan } from '../context/PlanContext';
import AgentGate from '../components/AgentGate';
import React, { useEffect, useState } from 'react';
import { useTimeline } from '../hooks/useTimeline';

const CAT_META = {
  prep:        { color:'var(--purple)', label:'Prep' },
  ceremony:    { color:'var(--rose)',   label:'Ceremony' },
  vendor:      { color:'var(--amber)',  label:'Vendor' },
  food:        { color:'var(--green)',  label:'Food' },
  celebration: { color:'var(--gold)',   label:'Celebration' },
  travel:      { color:'#5bc4e0',       label:'Travel' },
  buffer:      { color:'var(--text-muted)', label:'Buffer' },
};

const PRIORITY_DOT = { high:'var(--rose)', medium:'var(--amber)', low:'var(--text-muted)' };

const RELIGIONS = ['Hindu','Muslim','Sikh','Christian','Jain','Buddhist','Civil/Court'];

const DEFAULT_BRIEF = {
  brideName:'', groomName:'', weddingDate:'', ceremonyTime:'7:00 PM',
  venue:'', city:'Ranchi', religion:'Hindu', guestCount:300,
  hasBaraat:true, hasMehendi:true, hasSangeet:true, hasHaldi:false,
  photographerName:'', catererName:'', decoratorName:'', customNotes:'',
};

export default function TimelineAgent() {
  const { hasPlan } = usePlan();
  if (!hasPlan) return <AgentGate agentName="Timeline Agent" icon="" />;
  const { events, tips, agentNote, meta, loading, error, generated, load, generate, toggleComplete } = useTimeline();

  const [tab, setTab] = useState('build');
  const [brief, setBrief] = useState(DEFAULT_BRIEF);
  const [filterCat, setFilterCat] = useState('all');

  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (generated) setTab('timeline'); }, [generated]);

  const setB  = k => e => setBrief(b => ({ ...b, [k]: e.target.value }));
  const setBool = k => e => setBrief(b => ({ ...b, [k]: e.target.checked }));

  const filtered = filterCat === 'all' ? events : events.filter(e => e.category === filterCat);
  const completed = events.filter(e => e.completed).length;
  const progress  = events.length ? Math.round((completed / events.length) * 100) : 0;

  const handlePrint = () => {
    const w = window.open('', '_blank');
    const rows = events.map(e => `
      <tr style="border-bottom:1px solid #eee">
        <td style="padding:8px 12px;font-weight:600;white-space:nowrap">${e.time}</td>
        <td style="padding:8px 12px;color:#666">${e.duration}</td>
        <td style="padding:8px 12px;font-weight:500">${e.event}</td>
        <td style="padding:8px 12px;color:#555">${e.description}</td>
        <td style="padding:8px 12px;color:#888">${e.assignedTo}</td>
      </tr>`).join('');
    w.document.write(`
      <html><head><title>HeartBound IQ Wedding Timeline - ${meta?.brideName} & ${meta?.groomName}</title>
      <style>body{font-family:Georgia,serif;margin:40px}h1{color:#C8667A}table{width:100%;border-collapse:collapse}th{background:#f5e8ec;padding:10px 12px;text-align:left;font-size:13px}</style></head>
      <body>
        <h1>Wedding Timeline</h1>
        <p style="color:#888;margin-bottom:24px">${meta?.brideName} & ${meta?.groomName} | ${meta?.weddingDate || ''}</p>
        <table><thead><tr><th>Time</th><th>Duration</th><th>Event</th><th>Description</th><th>Assigned To</th></tr></thead>
        <tbody>${rows}</tbody></table>
        <p style="margin-top:32px;color:#aaa;font-size:12px">Generated by HeartBound IQ AI Wedding Planner</p>
      </body></html>`);
    w.document.close(); w.print();
  };

  return (
    <>
      <div className="page-header">
        <p className="page-header__eyebrow">Agent 06</p>
        <h1 className="page-header__title">Timeline <em>Agent</em></h1>
        <p className="page-header__sub">Build a complete wedding day schedule from morning prep to final farewell. AI-generated, printable, and trackable on the day.</p>
      </div>

      <div className="content">
        <div style={{ display:'flex', gap:6, marginBottom:20 }}>
          {[
            { id:'build',    label:'Build Schedule'  },
            { id:'timeline', label:'Day Timeline', badge: generated ? events.length : null },
            { id:'tips',     label:'Agent Tips', badge: tips.length || null },
          ].map(t => (
            <button key={t.id} onClick={() => setTab(t.id)}
              className={`btn ${tab === t.id ? 'btn--primary' : 'btn--dark'}`}
              style={{ flex:1, fontSize:13, gap:6 }}>
              {t.label}
              {t.badge ? <span style={{ background:'rgba(255,255,255,0.2)', borderRadius:10, padding:'1px 7px', fontSize:11 }}>{t.badge}</span> : null}
            </button>
          ))}
        </div>

        {tab === 'build' && (
          <div className="animate-in">
            <div className="card" style={{ marginBottom:16 }}>
              <p style={{ fontSize:11, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:12 }}>Couple details</p>
              <div className="form-grid" style={{ marginBottom:20 }}>
                <div className="field"><label className="label">Bride's name *</label><input className="input" value={brief.brideName} onChange={setB('brideName')} placeholder="e.g. Priya Sharma" /></div>
                <div className="field"><label className="label">Groom's name *</label><input className="input" value={brief.groomName} onChange={setB('groomName')} placeholder="e.g. Arjun Mehta" /></div>
                <div className="field"><label className="label">Wedding date</label><input className="input" type="date" value={brief.weddingDate} onChange={setB('weddingDate')} /></div>
                <div className="field"><label className="label">Ceremony start time</label><input className="input" value={brief.ceremonyTime} onChange={setB('ceremonyTime')} placeholder="e.g. 7:00 PM" /></div>
              </div>

              <p style={{ fontSize:11, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:12 }}>Venue and tradition</p>
              <div className="form-grid" style={{ marginBottom:20 }}>
                <div className="field"><label className="label">Venue name</label><input className="input" value={brief.venue} onChange={setB('venue')} placeholder="e.g. Grand Marigold Palace" /></div>
                <div className="field"><label className="label">City</label><input className="input" value={brief.city} onChange={setB('city')} placeholder="e.g. Ranchi" /></div>
                <div className="field">
                  <label className="label">Religion / tradition</label>
                  <select className="input" value={brief.religion} onChange={setB('religion')}>
                    {RELIGIONS.map(r => <option key={r}>{r}</option>)}
                  </select>
                </div>
                <div className="field"><label className="label">Guest count</label><input className="input" type="number" min="50" value={brief.guestCount} onChange={setB('guestCount')} /></div>
              </div>

              <p style={{ fontSize:11, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:12 }}>Events to include</p>
              <div style={{ display:'flex', flexWrap:'wrap', gap:10, marginBottom:20 }}>
                {[
                  { k:'hasBaraat',  label:'Baraat' },
                  { k:'hasMehendi', label:'Mehendi' },
                  { k:'hasSangeet', label:'Sangeet' },
                  { k:'hasHaldi',   label:'Haldi' },
                ].map(({ k, label }) => (
                  <label key={k} style={{ display:'flex', alignItems:'center', gap:8, cursor:'pointer', padding:'8px 14px', borderRadius:'var(--radius-sm)', border: brief[k] ? '1px solid var(--border-rose)' : '1px solid var(--border)', background: brief[k] ? 'var(--rose-dim)' : 'var(--bg-elevated)', fontSize:13, color: brief[k] ? 'var(--rose)' : 'var(--text-secondary)', transition:'all 0.15s' }}>
                    <input type="checkbox" checked={brief[k]} onChange={setBool(k)} style={{ accentColor:'var(--rose)', width:14, height:14 }} />
                    {label}
                  </label>
                ))}
              </div>

              <p style={{ fontSize:11, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:12 }}>Your vendors <span style={{ textTransform:'none', letterSpacing:0, fontWeight:400 }}>(optional - for personalised timings)</span></p>
              <div className="form-grid" style={{ marginBottom:20 }}>
                <div className="field"><label className="label">Photographer</label><input className="input" value={brief.photographerName} onChange={setB('photographerName')} placeholder="e.g. LensLove Studios" /></div>
                <div className="field"><label className="label">Caterer</label><input className="input" value={brief.catererName} onChange={setB('catererName')} placeholder="e.g. Grand Feast" /></div>
                <div className="field"><label className="label">Decorator</label><input className="input" value={brief.decoratorName} onChange={setB('decoratorName')} placeholder="e.g. Blooms and Beyond" /></div>
              </div>

              <div className="field" style={{ marginBottom:20 }}>
                <label className="label">Special notes <span>(optional)</span></label>
                <input className="input" value={brief.customNotes} onChange={setB('customNotes')} placeholder="e.g. venue curfew at 11 PM, separate rooms for families, outdoor ceremony" />
              </div>

              {error && <div className="error-box" style={{ marginBottom:12 }}>{error}</div>}

              <button className="btn btn--primary btn--full btn--lg" onClick={() => generate(brief)}
                disabled={loading || !brief.brideName || !brief.groomName}>
                {loading ? <><span className="spinner"/> Building your timeline...</> : 'Generate Wedding Timeline'}
              </button>
            </div>
          </div>
        )}

        {tab === 'timeline' && (
          <div className="animate-in">
            {!generated ? (
              <div className="empty card">
                <span className="empty__icon"></span>
                Fill in the Build tab and generate your timeline first.
              </div>
            ) : (
              <>
                {agentNote && (
                  <div className="agent-note" style={{ marginBottom:16 }}>
                    <span className="agent-note__icon">i</span>
                    <div>
                      <p className="agent-note__label">HeartBound IQ Timeline Agent</p>
                      <p className="agent-note__text">{agentNote}</p>
                    </div>
                  </div>
                )}

                <div className="card" style={{ marginBottom:16, padding:'14px 18px' }}>
                  <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:8 }}>
                    <span style={{ fontSize:13, color:'var(--text-secondary)' }}>Day-of progress</span>
                    <span style={{ fontSize:13, fontWeight:500, color: progress === 100 ? 'var(--green)' : 'var(--text-primary)' }}>{completed}/{events.length} done</span>
                  </div>
                  <div style={{ background:'var(--bg-elevated)', borderRadius:6, height:8, overflow:'hidden' }}>
                    <div style={{ width:`${progress}%`, height:'100%', background: progress === 100 ? 'var(--green)' : 'var(--rose)', borderRadius:6, transition:'width 0.4s ease' }} />
                  </div>
                </div>

                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:14, flexWrap:'wrap', gap:8 }}>
                  <div style={{ display:'flex', gap:6, flexWrap:'wrap' }}>
                    <button onClick={() => setFilterCat('all')}
                      className={`badge ${filterCat === 'all' ? 'badge--rose' : 'badge--gray'}`}
                      style={{ cursor:'pointer', border:'none', padding:'5px 12px', fontSize:12 }}>All</button>
                    {Object.entries(CAT_META).map(([k, m]) => (
                      <button key={k} onClick={() => setFilterCat(k)}
                        className={`badge ${filterCat === k ? 'badge--rose' : 'badge--gray'}`}
                        style={{ cursor:'pointer', border:'none', padding:'5px 12px', fontSize:12 }}>
                        {m.label}
                      </button>
                    ))}
                  </div>
                  <button className="btn btn--dark" style={{ height:34, fontSize:12 }} onClick={handlePrint}>
                    Print Timeline
                  </button>
                </div>

                <div style={{ position:'relative' }}>
                  <div style={{ position:'absolute', left:19, top:0, bottom:0, width:2, background:'var(--border)', borderRadius:1 }} />

                  <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                    {filtered.map((ev, i) => {
                      const cm = CAT_META[ev.category] || CAT_META.buffer;
                      return (
                        <div key={ev.id} className="animate-in" style={{ display:'flex', gap:14, animationDelay:`${i*0.04}s`, position:'relative' }}>
                          <div style={{ width:40, flexShrink:0, display:'flex', alignItems:'flex-start', paddingTop:14, justifyContent:'center', position:'relative', zIndex:1 }}>
                            <div style={{ width:14, height:14, borderRadius:'50%', background: ev.completed ? 'var(--green)' : cm.color, border:'2px solid var(--bg)', transition:'background 0.2s', cursor:'pointer' }}
                              onClick={() => toggleComplete(ev.id, !ev.completed)} />
                          </div>

                          <div className="card" style={{ flex:1, padding:'12px 16px', opacity: ev.completed ? 0.55 : 1, transition:'opacity 0.2s', borderLeft: `3px solid ${cm.color}`, borderRadius:'0 var(--radius-md) var(--radius-md) 0' }}>
                            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', gap:8, marginBottom:4 }}>
                              <div style={{ display:'flex', alignItems:'center', gap:8, flexWrap:'wrap' }}>
                                <span style={{ fontSize:13, fontWeight:500, color:'var(--text-primary)', textDecoration: ev.completed ? 'line-through' : 'none' }}>{ev.event}</span>
                                <span style={{ width:6, height:6, borderRadius:'50%', background:PRIORITY_DOT[ev.priority], display:'inline-block', flexShrink:0 }} title={`${ev.priority} priority`} />
                              </div>
                              <div style={{ display:'flex', alignItems:'center', gap:6, flexShrink:0 }}>
                                <span style={{ fontSize:11, color: cm.color, background:'var(--bg-elevated)', padding:'2px 8px', borderRadius:10 }}>{cm.label}</span>
                              </div>
                            </div>

                            <div style={{ display:'flex', gap:12, marginBottom:6, flexWrap:'wrap' }}>
                              <span style={{ fontSize:12, fontWeight:500, color:'var(--rose)' }}>{ev.time}</span>
                              <span style={{ fontSize:12, color:'var(--text-muted)' }}>{ev.duration}</span>
                              <span style={{ fontSize:12, color:'var(--text-muted)' }}>{ev.assignedTo}</span>
                            </div>

                            <p style={{ fontSize:13, color:'var(--text-secondary)', lineHeight:1.5 }}>{ev.description}</p>

                            <button onClick={() => toggleComplete(ev.id, !ev.completed)}
                              className={`badge ${ev.completed ? 'badge--green' : 'badge--gray'}`}
                              style={{ cursor:'pointer', border:'none', marginTop:8, fontSize:11 }}>
                              {ev.completed ? 'Done' : 'Mark done'}
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </>
            )}
          </div>
        )}

        {tab === 'tips' && (
          <div className="animate-in">
            {!tips.length ? (
              <div className="empty card">
                <span className="empty__icon"></span>
                Generate your timeline first to get personalised tips.
              </div>
            ) : (
              <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
                <div className="agent-note" style={{ marginBottom:4 }}>
                  <span className="agent-note__icon">i</span>
                  <div>
                    <p className="agent-note__label">HeartBound IQ Timeline Agent</p>
                    <p className="agent-note__text">Here are personalised tips to make your wedding day run smoothly:</p>
                  </div>
                </div>
                {tips.map((tip, i) => (
                  <div key={i} className="card animate-in" style={{ display:'flex', gap:14, alignItems:'flex-start', animationDelay:`${i*0.08}s` }}>
                    <div style={{ width:28, height:28, borderRadius:'50%', background:'var(--gold-dim)', border:'1px solid rgba(212,168,75,0.3)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:12, color:'var(--gold)', flexShrink:0, fontFamily:'var(--font-display)', fontWeight:500, paddingTop:1 }}>
                      {i + 1}
                    </div>
                    <p style={{ fontSize:14, color:'var(--text-secondary)', lineHeight:1.7, paddingTop:3 }}>{tip}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </>
  );
}
